FROM emd-test:latest

RUN rm /etc/dpkg/dpkg.cfg.d/docker-apt-speedup
RUN apt update && env DEBIAN_FRONTEND=noninteractive apt-get install --yes build-essential ca-certificates libssl-dev software-properties-common wget curl git
