FROM debian:stable-slim

RUN mv /etc/apt/apt.conf.d/docker-clean /etc/apt/docker-clean-disabled
RUN apt update && env DEBIAN_FRONTEND=noninteractive apt-get install --yes --download-only build-essential ca-certificates libssl-dev software-properties-common wget curl git
